### ISSUE TITLE
Tracking issue for adding NIP-13 (POW) to NDK

### ISSUE THREAD

**Issue by erskingardner** [nostr-dev-kit/ndk#197]
This is a tracking issue for changes needed to add NIP-13 to NDK.

- [ ] Figure out TS webworker
- [ ] Turn Miner into class to handle Isomorphic webworker with node.js
- [ ] Tests for all files
- [ ] Add event ID in the `handleMinedPow` function (in nip13.ts)

**Comment by arkin0x** [comment]
Ref this for workers https://github.com/v0l/snort/blob/a3f139399973df4caa1e2e20b83ce80663fae90b/packages/system/src/pow.ts#L4
